### PR TITLE
Update library to version 2.9.4

### LINKED ISSUE #2: Update library to version 2.9.4
Update the library to [version 2.9.4](https://github.com/nodejs/http-parser/releases/tag/v2.9.4).
Since the library has no dependencies, it will likely not need other version bumps.

**Hackaton points**: 20

### PR DESCRIPTION
**Pull request by DeliaPavel**
Signed-off-by: Delia-Maria Pavel <delia_maria.pavel@stud.acs.upb.ro>

### CODE REVIEW

**Comment by DeliaPavel** [comment]
solves issue: #2

**Review by StefanJum — APPROVED** [review]
Good job @DeliaPavel, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by eduardvintila — APPROVED** [review]
All good.
Reviewed-by: Eduard Vintilă eduard.vintila47@gmail.com

**Comment by razvand** [comment]
@DeliaPavel , please use the same e-mail address for the commit author and for the signing. Best way is to configure your e-mail address globally[1] and use that from now on.

You can reset your author e-mail to the one you configured by using `git commit --amend --no-edit --reset-author`. You can update the `Signed-off-by` e-mail address by using `git commit --amend` and updating it manually in the interactive editor screen.

@eduardvintila , @StefanJum , pay attention to author name / e-mail and signed-off name / e-mail and their consistency.

[1] https://gitimmersion.com/lab_01.html

**Review by razvand — APPROVED** [review]
Thanks, @DeliaPavel 

Reviewed-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>
Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

**Pull request closed without merging**
